"""
hermes-claude-auth bootstrap — Claude Code OAuth bypass for hermes-agent.
=======================================================================

Installed into the hermes-agent venv's site-packages as
``_hermes_claude_auth_bootstrap.py``. A sibling ``hermes_claude_auth.pth``
imports this module during interpreter startup, before ``sitecustomize`` is
resolved, then this module registers a MetaPathFinder hook for
``agent.anthropic_adapter``.

The .pth route avoids Debian/Ubuntu's global ``sitecustomize.py`` collision:
those distros ship an apport ``/usr/lib/pythonX.Y/sitecustomize.py`` that can
shadow venv-local hooks. The .pth shim is processed earlier and works across
platforms.

To disable: run ``uninstall.sh`` or delete both ``hermes_claude_auth.pth`` and
``_hermes_claude_auth_bootstrap.py`` from site-packages, then restart
hermes-gateway.

DO NOT EDIT THIS FILE IN THE VENV — it will be overwritten on next install.
Edit the source in the hermes-claude-auth repo instead.
"""
# hermes-claude-auth managed — do not remove this marker

from __future__ import annotations

import os
import sys

_PATCHES_DIR = os.environ.get("HERMES_PATCHES_DIR", "")
if not _PATCHES_DIR or not os.path.isdir(_PATCHES_DIR):
    _candidates: list[str] = []
    _localappdata = os.environ.get("LOCALAPPDATA", "")
    if _localappdata:
        _candidates.append(os.path.join(_localappdata, "hermes", "patches"))
    _candidates.append(os.path.expanduser("~/.hermes/patches"))
    for _candidate in _candidates:
        if os.path.isdir(_candidate):
            _PATCHES_DIR = _candidate
            break
    else:
        _PATCHES_DIR = _candidates[-1]
_TARGET_MODULE = "agent.anthropic_adapter"

if os.path.isdir(_PATCHES_DIR) and _PATCHES_DIR not in sys.path:
    sys.path.insert(0, _PATCHES_DIR)


def _apply_bypass_patch(module) -> None:  # type: ignore[no-untyped-def]
    """Apply anthropic_billing_bypass to a loaded Hermes module.

    Kept as a small helper so direct patcher tests and the import hook share
    the same missing-module/noop behavior.
    """
    try:
        import anthropic_billing_bypass
    except ImportError:
        return
    anthropic_billing_bypass.apply_patches(module)


def _patch_anthropic_adapter(module) -> None:  # type: ignore[no-untyped-def]
    _apply_bypass_patch(module)


def _patch_error_classifier(module) -> None:  # type: ignore[no-untyped-def]
    _apply_bypass_patch(module)


def _install_hook() -> None:
    if getattr(sys, "_hermes_claude_auth_hook_installed", False):
        return

    try:
        from importlib.abc import MetaPathFinder
        from importlib.util import find_spec
    except ImportError:
        return

    class _ClaudeCodeBypassFinder(MetaPathFinder):
        _patched = False

        def find_spec(self, fullname, path=None, target=None):  # type: ignore[override]
            if fullname != _TARGET_MODULE or self._patched:
                return None

            if self in sys.meta_path:
                sys.meta_path.remove(self)
            try:
                spec = find_spec(fullname)
            finally:
                if self not in sys.meta_path:
                    sys.meta_path.insert(0, self)

            if spec is None or spec.loader is None:
                return None

            original_exec = getattr(spec.loader, "exec_module", None)
            if not callable(original_exec):
                return None

            finder = self

            def patched_exec(module):  # type: ignore[no-untyped-def]
                original_exec(module)
                finder._patched = True
                try:
                    _patch_anthropic_adapter(module)
                except Exception as exc:
                    import traceback

                    sys.stderr.write(
                        f"[hermes-claude-auth] bypass failed: "
                        f"{type(exc).__name__}: {exc}\n"
                    )
                    traceback.print_exc(file=sys.stderr)

            spec.loader.exec_module = patched_exec  # type: ignore[attr-defined]
            return spec

    sys.meta_path.insert(0, _ClaudeCodeBypassFinder())
    setattr(sys, "_hermes_claude_auth_hook_installed", True)


try:
    _install_hook()
except Exception as _exc:
    sys.stderr.write(f"[hermes-claude-auth] hook install failed: {_exc}\n")
